# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter_action

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk --debug
    
    - run: mv build/app/outputs/flutter-apk/app-debug.apk build/app/outputs/flutter-apk/crypto-info_debug.apk
    
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: Crypto-Info Debug APK
        path: build/app/outputs/flutter-apk/crypto-info_debug.apk
        
